/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserGuideRouteImport } from './routes/user-guide'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PocketRouteImport } from './routes/pocket'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as PocketInstallRouteImport } from './routes/pocket.install'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSweepRouteImport } from './routes/api/public/hooks/sweep'

const UserGuideRoute = UserGuideRouteImport.update({
  id: '/user-guide',
  path: '/user-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PocketRoute = PocketRouteImport.update({
  id: '/pocket',
  path: '/pocket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const PocketInstallRoute = PocketInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => PocketRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSweepRoute = ApiPublicHooksSweepRouteImport.update({
  id: '/api/public/hooks/sweep',
  path: '/api/public/hooks/sweep',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/demo': typeof DemoRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/how-to-play': typeof HowToPlayRoute
  '/login': typeof LoginRoute
  '/pocket': typeof PocketRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shop': typeof ShopRouteWithChildren
  '/user-guide': typeof UserGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/api/bot': typeof ApiBotRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/pocket/install': typeof PocketInstallRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/api/public/hooks/sweep': typeof ApiPublicHooksSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/demo': typeof DemoRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/how-to-play': typeof HowToPlayRoute
  '/login': typeof LoginRoute
  '/pocket': typeof PocketRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shop': typeof ShopRouteWithChildren
  '/user-guide': typeof UserGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/api/bot': typeof ApiBotRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/pocket/install': typeof PocketInstallRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/api/public/hooks/sweep': typeof ApiPublicHooksSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/demo': typeof DemoRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/how-to-play': typeof HowToPlayRoute
  '/login': typeof LoginRoute
  '/pocket': typeof PocketRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shop': typeof ShopRouteWithChildren
  '/user-guide': typeof UserGuideRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/api/bot': typeof ApiBotRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/pocket/install': typeof PocketInstallRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/api/public/hooks/sweep': typeof ApiPublicHooksSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coming-soon'
    | '/demo'
    | '/disclaimer'
    | '/faq'
    | '/how-to-play'
    | '/login'
    | '/pocket'
    | '/pricing'
    | '/refund-policy'
    | '/shop'
    | '/user-guide'
    | '/admin'
    | '/app'
    | '/portal'
    | '/api/bot'
    | '/checkout/return'
    | '/pocket/install'
    | '/shop/$slug'
    | '/shop/cart'
    | '/api/public/hooks/sweep'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coming-soon'
    | '/demo'
    | '/disclaimer'
    | '/faq'
    | '/how-to-play'
    | '/login'
    | '/pocket'
    | '/pricing'
    | '/refund-policy'
    | '/shop'
    | '/user-guide'
    | '/admin'
    | '/app'
    | '/portal'
    | '/api/bot'
    | '/checkout/return'
    | '/pocket/install'
    | '/shop/$slug'
    | '/shop/cart'
    | '/api/public/hooks/sweep'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/coming-soon'
    | '/demo'
    | '/disclaimer'
    | '/faq'
    | '/how-to-play'
    | '/login'
    | '/pocket'
    | '/pricing'
    | '/refund-policy'
    | '/shop'
    | '/user-guide'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/portal'
    | '/api/bot'
    | '/checkout/return'
    | '/pocket/install'
    | '/shop/$slug'
    | '/shop/cart'
    | '/api/public/hooks/sweep'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DemoRoute: typeof DemoRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  HowToPlayRoute: typeof HowToPlayRoute
  LoginRoute: typeof LoginRoute
  PocketRoute: typeof PocketRouteWithChildren
  PricingRoute: typeof PricingRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShopRoute: typeof ShopRouteWithChildren
  UserGuideRoute: typeof UserGuideRoute
  ApiBotRoute: typeof ApiBotRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicHooksSweepRoute: typeof ApiPublicHooksSweepRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-guide': {
      id: '/user-guide'
      path: '/user-guide'
      fullPath: '/user-guide'
      preLoaderRoute: typeof UserGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pocket': {
      id: '/pocket'
      path: '/pocket'
      fullPath: '/pocket'
      preLoaderRoute: typeof PocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/pocket/install': {
      id: '/pocket/install'
      path: '/install'
      fullPath: '/pocket/install'
      preLoaderRoute: typeof PocketInstallRouteImport
      parentRoute: typeof PocketRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sweep': {
      id: '/api/public/hooks/sweep'
      path: '/api/public/hooks/sweep'
      fullPath: '/api/public/hooks/sweep'
      preLoaderRoute: typeof ApiPublicHooksSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PocketRouteChildren {
  PocketInstallRoute: typeof PocketInstallRoute
}

const PocketRouteChildren: PocketRouteChildren = {
  PocketInstallRoute: PocketInstallRoute,
}

const PocketRouteWithChildren =
  PocketRoute._addFileChildren(PocketRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCartRoute: typeof ShopCartRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopCartRoute: ShopCartRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ComingSoonRoute: ComingSoonRoute,
  DemoRoute: DemoRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  HowToPlayRoute: HowToPlayRoute,
  LoginRoute: LoginRoute,
  PocketRoute: PocketRouteWithChildren,
  PricingRoute: PricingRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShopRoute: ShopRouteWithChildren,
  UserGuideRoute: UserGuideRoute,
  ApiBotRoute: ApiBotRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicHooksSweepRoute: ApiPublicHooksSweepRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
